// obtiene un chofer por dni de ZAP
GET http://10.10.0.223:8090/appointments/BACTSSA/0/10?fechaInicio=2017-01-01
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRyZXllc0BwdWVydG9idWVub3NhaXJlcy5nb2IuYXIifQ.gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw
