
POST http://10.10.0.223:8090/gates/setStatus
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNvcG9ydGVfY3RzQGJhY3Rzc2EuY29tLmFyIn0.bBSqdwesWimlT8rFGA7sKLKbPdxauY8HdrTTt7BLpBU
Content-Type: application/json

{
    "id": 10451570,
    "status": 1
}
//add Gate
POST http://10.10.0.223:8080/gate
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRyZXllc0BwdWVydG9idWVub3NhaXJlcy5nb2IuYXIifQ.gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw
Content-Type: application/json

{
    "contenedor": "XXXX1111111",
    "gateTimestamp": "2018-01-03T00:00:00.000-03:00",
    "patenteCamion": "AAA112",
    "mov": "EXPO",
    "carga": "LL",
    "tipo": "IN",
    "terminal": "ZAP",
    "dni": 23250578
}
//delete gate
POST http://190.221.146.243:8090/gates/delete
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRyZXllc0BwdWVydG9idWVub3NhaXJlcy5nb2IuYXIifQ.gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw
Content-Type: application/json

{
    "id": 10521571
}

//getById
GET http://190.221.146.245:8090/gates/ById/10474543
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRyZXllc0BwdWVydG9idWVub3NhaXJlcy5nb2IuYXIifQ.gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw

//getGates CSV
GET http://10.10.0.223:8090/gates/BACTSSA/down?fechaInicio=2018-01-08
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5vcmVwbHlAcHVlcnRvYnVlbm9zYWlyZXMuZ29iLmFyIn0.g4d2NfkU5vIYfkG2QuEsKpTiT_-jpYLK5QGriiKa4Ck


